// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ReqnrollProject1.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class COFFOptionalHeaderStandardFieldsFeature
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "COFFOptionalHeaderStandardFields.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, System.Threading.Thread.CurrentThread.ManagedThreadId.ToString());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "COFFOptionalHeaderStandardFields", "\tIn order to dissect a PECOFF binary file\r\n\tAs an interested party\r\n\tI want to re" +
                    "ad the COFFOptionalHeaderStandardFields from the file\r\n\tAnd I want to see the co" +
                    "mponent parts", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "COFFOptionalHeaderStandardFields")))
            {
                await global::ReqnrollProject1.Features.COFFOptionalHeaderStandardFieldsFeature.FeatureSetupAsync(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile(string fileName, string magic, string majorLinkerVersion, string minorLinkerVersion, string sizeOfCode, string sizeOfInitializedData, string sizeOfUninitializedData, string addressOfEntryPoint, string baseOfCode, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("File Name", fileName);
            argumentsOfScenario.Add("Magic", magic);
            argumentsOfScenario.Add("MajorLinkerVersion", majorLinkerVersion);
            argumentsOfScenario.Add("MinorLinkerVersion", minorLinkerVersion);
            argumentsOfScenario.Add("SizeOfCode", sizeOfCode);
            argumentsOfScenario.Add("SizeOfInitializedData", sizeOfInitializedData);
            argumentsOfScenario.Add("SizeOfUninitializedData", sizeOfUninitializedData);
            argumentsOfScenario.Add("AddressOfEntryPoint", addressOfEntryPoint);
            argumentsOfScenario.Add("BaseOfCode", baseOfCode);
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
 await testRunner.GivenAsync(string.Format("a PECOFF binary file named {0}", fileName), ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
 await testRunner.WhenAsync("I read in the MSDOS20Section", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
 await testRunner.AndAsync("I read in the COFFOptionalHeaderStandardFields", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
 await testRunner.ThenAsync(string.Format("the Magic shoud be {0}", magic), ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 12
 await testRunner.AndAsync(string.Format("the MajorLinkerVersion should be {0}", majorLinkerVersion), ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
 await testRunner.AndAsync(string.Format("the MinorLinkerVersion should be {0}", minorLinkerVersion), ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
 await testRunner.AndAsync(string.Format("the SizeOfCode should be {0}", sizeOfCode), ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.AndAsync(string.Format("the SizeOfInitializedData should be {0}", sizeOfInitializedData), ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.AndAsync(string.Format("the SizeOfUninitializedData should be {0}", sizeOfUninitializedData), ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.AndAsync(string.Format("the AddressOfEntryPoint should be {0}", addressOfEntryPoint), ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync(string.Format("the BaseOfCode should be {0}", baseOfCode), ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_CSC_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_CSC_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_CSC_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "1024")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x23AE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_CSC_2_0_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_CSC_2.0.exe", "0x10B", "0x8", "0x0", "1024", "1536", "0", "0x23AE", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_CSC_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_CSC_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_CSC_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "1024")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2048")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x23AE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_CSC_3_5_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_CSC_3.5.exe", "0x10B", "0x8", "0x0", "1024", "2048", "0", "0x23AE", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_CSC_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_CSC_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_CSC_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0xB")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "1024")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2048")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x23AE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_CSC_4_0_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_CSC_4.0.exe", "0x10B", "0xB", "0x0", "1024", "2048", "0", "0x23AE", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_VS_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "2048")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x27AA")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_VS_2_0_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_VS_2.0.exe", "0x10B", "0x30", "0x0", "2048", "2560", "0", "0x27AA", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_VS_3.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_3.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_3.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "2048")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x27A6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_VS_3_0_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_VS_3.0.exe", "0x10B", "0x30", "0x0", "2048", "2560", "0", "0x27A6", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_VS_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "2048")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x27A6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_VS_3_5_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_VS_3.5.exe", "0x10B", "0x30", "0x0", "2048", "2560", "0", "0x27A6", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_VS_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x283E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_VS_4_5_1_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_VS_4.5.1.exe", "0x10B", "0x30", "0x0", "2560", "2560", "0", "0x283E", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_VS_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x283E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_VS_4_5_2_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_VS_4.5.2.exe", "0x10B", "0x30", "0x0", "2560", "2560", "0", "0x283E", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_VS_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x2832")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_VS_4_5_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_VS_4.5.exe", "0x10B", "0x30", "0x0", "2560", "2560", "0", "0x2832", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_VS_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x283E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_VS_4_6_1_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_VS_4.6.1.exe", "0x10B", "0x30", "0x0", "2560", "2560", "0", "0x283E", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_VS_4.6.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.6.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.6.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2048")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x282A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_VS_4_6_2_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_VS_4.6.2.exe", "0x10B", "0x30", "0x0", "2560", "2048", "0", "0x282A", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_VS_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x2832")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_VS_4_6_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_VS_4.6.exe", "0x10B", "0x30", "0x0", "2560", "2560", "0", "0x2832", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_VS_4.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "2560")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2048")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x282A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_VS_4_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_VS_4.exe", "0x10B", "0x30", "0x0", "2560", "2048", "0", "0x282A", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_VS_Core_1.0.dll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_Core_1.0.dll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_Core_1.0.dll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "2048")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "2048")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x27FA")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_VS_Core_1_0_Dll()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_VS_Core_1.0.dll", "0x10B", "0x30", "0x0", "2048", "2048", "0", "0x27FA", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_Xamarin_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x24FE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_Xamarin_2_0_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_Xamarin_2.0.exe", "0x10B", "0x8", "0x0", "1536", "1536", "0", "0x24FE", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_Xamarin_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x257E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_Xamarin_4_0_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_Xamarin_4.0.exe", "0x10B", "0x8", "0x0", "1536", "1536", "0", "0x257E", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_Xamarin_4.0Client.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.0Client.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.0Client.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x25AE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_Xamarin_4_0Client_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_Xamarin_4.0Client.exe", "0x10B", "0x8", "0x0", "1536", "1536", "0", "0x25AE", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_Xamarin_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x258E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_Xamarin_4_5_1_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_Xamarin_4.5.1.exe", "0x10B", "0x8", "0x0", "1536", "1536", "0", "0x258E", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_Xamarin_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x258E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_Xamarin_4_5_2_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_Xamarin_4.5.2.exe", "0x10B", "0x8", "0x0", "1536", "1536", "0", "0x258E", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_Xamarin_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x257E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_Xamarin_4_5_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_Xamarin_4.5.exe", "0x10B", "0x8", "0x0", "1536", "1536", "0", "0x257E", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_Xamarin_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x258E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_Xamarin_4_6_1_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_Xamarin_4.6.1.exe", "0x10B", "0x8", "0x0", "1536", "1536", "0", "0x258E", "0x2000", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the COFFOptionalHeaderStandardFields from a given PECOFF binary file: HelloW" +
            "orld_Xamarin_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "COFFOptionalHeaderStandardFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Magic", "0x10B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MajorLinkerVersion", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MinorLinkerVersion", "0x0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfCode", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfInitializedData", "1536")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SizeOfUninitializedData", "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddressOfEntryPoint", "0x257E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BaseOfCode", "0x2000")]
        public async System.Threading.Tasks.Task ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile_HelloWorld_Xamarin_4_6_Exe()
        {
#line 7
await this.ReadTheCOFFOptionalHeaderStandardFieldsFromAGivenPECOFFBinaryFile("HelloWorld_Xamarin_4.6.exe", "0x10B", "0x8", "0x0", "1536", "1536", "0", "0x257E", "0x2000", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
