// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DissectPECOFFBinary.SpecFlow
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class TextSectionFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TextSection.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "TextSection", "\tIn order to dissect a PECOFF binary file\r\n\tAs an interested party\r\n\tI want to re" +
                    "ad the .Text from the file\r\n\tAnd I want to see the component parts", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "TextSection")))
            {
                global::DissectPECOFFBinary.SpecFlow.TextSectionFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries(string fileName, string numberOfEntries, string entryValues, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Read the Import Address Table from a file check the number of entries", exampleTags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given(string.Format("a PECOFF binary file named {0}", fileName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When("I read in the MSDOS20Section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.And("I read in the COFFHeader", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("I read in the COFFOptionalHeaderStandardFields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("I read in the OptionalHeaderDataDirectories", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("I read the SectionTables", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("I read the Import Address Table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.Then(string.Format("the number of entries should be {0}", numberOfEntries), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
 testRunner.And(string.Format("the values should be {0}", entryValues), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_CSC_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_CSC_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_CSC_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2390,0x0,0x48,0x50002,0x2070,0x2EC,0x1,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_CSC_2_0_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_CSC_2.0.exe", "0x8", "0x2390,0x0,0x48,0x50002,0x2070,0x2EC,0x1,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_CSC_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_CSC_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_CSC_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2390,0x0,0x48,0x50002,0x2070,0x2EC,0x1,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_CSC_3_5_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_CSC_3.5.exe", "0x8", "0x2390,0x0,0x48,0x50002,0x2070,0x2EC,0x1,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_CSC_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_CSC_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_CSC_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2390,0x0,0x48,0x50002,0x2070,0x2EC,0x1,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_CSC_4_0_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_CSC_4.0.exe", "0x8", "0x2390,0x0,0x48,0x50002,0x2070,0x2EC,0x1,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_VS_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x278C,0x0,0x48,0x50002,0x2070,0x5B0,0x1,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_VS_2_0_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_VS_2.0.exe", "0x8", "0x278C,0x0,0x48,0x50002,0x2070,0x5B0,0x1,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_VS_3.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_3.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_3.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2788,0x0,0x48,0x50002,0x2070,0x5AC,0x1,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_VS_3_0_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_VS_3.0.exe", "0x8", "0x2788,0x0,0x48,0x50002,0x2070,0x5AC,0x1,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_VS_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_3.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2788,0x0,0x48,0x50002,0x2070,0x5AC,0x1,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_VS_3_5_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_VS_3.5.exe", "0x8", "0x2788,0x0,0x48,0x50002,0x2070,0x5AC,0x1,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_VS_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2820,0x0,0x48,0x50002,0x2070,0x644,0x20003,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_VS_4_5_1_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_VS_4.5.1.exe", "0x8", "0x2820,0x0,0x48,0x50002,0x2070,0x644,0x20003,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_VS_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2820,0x0,0x48,0x50002,0x2070,0x644,0x20003,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_VS_4_5_2_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_VS_4.5.2.exe", "0x8", "0x2820,0x0,0x48,0x50002,0x2070,0x644,0x20003,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_VS_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2814,0x0,0x48,0x50002,0x2070,0x638,0x20003,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_VS_4_5_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_VS_4.5.exe", "0x8", "0x2814,0x0,0x48,0x50002,0x2070,0x638,0x20003,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_VS_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2820,0x0,0x48,0x50002,0x2070,0x644,0x20003,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_VS_4_6_1_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_VS_4.6.1.exe", "0x8", "0x2820,0x0,0x48,0x50002,0x2070,0x644,0x20003,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_VS_4.6.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.6.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.6.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x280C,0x0,0x48,0x50002,0x2070,0x630,0x20003,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_VS_4_6_2_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_VS_4.6.2.exe", "0x8", "0x280C,0x0,0x48,0x50002,0x2070,0x630,0x20003,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_VS_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2814,0x0,0x48,0x50002,0x2070,0x638,0x20003,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_VS_4_6_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_VS_4.6.exe", "0x8", "0x2814,0x0,0x48,0x50002,0x2070,0x638,0x20003,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_VS_4.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_4.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_4.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x280C,0x0,0x48,0x50002,0x2070,0x630,0x1,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_VS_4_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_VS_4.exe", "0x8", "0x280C,0x0,0x48,0x50002,0x2070,0x630,0x1,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_VS_Core_1.0.dll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_VS_Core_1.0.dll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_VS_Core_1.0.dll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x27DC,0x0,0x48,0x50002,0x20A4,0x5CC,0x1,0x6000001")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_VS_Core_1_0_Dll()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_VS_Core_1.0.dll", "0x8", "0x27DC,0x0,0x48,0x50002,0x20A4,0x5CC,0x1,0x6000001", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_Xamarin_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_2.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x24E0,0x0,0x48,0x50002,0x2070,0x440,0x3,0x6000002")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_Xamarin_2_0_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_Xamarin_2.0.exe", "0x8", "0x24E0,0x0,0x48,0x50002,0x2070,0x440,0x3,0x6000002", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_Xamarin_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.0.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2560,0x0,0x48,0x50002,0x2070,0x4C0,0x3,0x6000002")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_Xamarin_4_0_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_Xamarin_4.0.exe", "0x8", "0x2560,0x0,0x48,0x50002,0x2070,0x4C0,0x3,0x6000002", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_Xamarin_4.0Client.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.0Client.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.0Client.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2590,0x0,0x48,0x50002,0x2070,0x4E8,0x3,0x6000002")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_Xamarin_4_0Client_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_Xamarin_4.0Client.exe", "0x8", "0x2590,0x0,0x48,0x50002,0x2070,0x4E8,0x3,0x6000002", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_Xamarin_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.5.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2570,0x0,0x48,0x50002,0x2070,0x4C8,0x3,0x6000002")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_Xamarin_4_5_1_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_Xamarin_4.5.1.exe", "0x8", "0x2570,0x0,0x48,0x50002,0x2070,0x4C8,0x3,0x6000002", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_Xamarin_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.5.2.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2570,0x0,0x48,0x50002,0x2070,0x4C8,0x3,0x6000002")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_Xamarin_4_5_2_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_Xamarin_4.5.2.exe", "0x8", "0x2570,0x0,0x48,0x50002,0x2070,0x4C8,0x3,0x6000002", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_Xamarin_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.5.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2560,0x0,0x48,0x50002,0x2070,0x4C0,0x3,0x6000002")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_Xamarin_4_5_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_Xamarin_4.5.exe", "0x8", "0x2560,0x0,0x48,0x50002,0x2070,0x4C0,0x3,0x6000002", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_Xamarin_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.6.1.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2570,0x0,0x48,0x50002,0x2070,0x4C8,0x3,0x6000002")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_Xamarin_4_6_1_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_Xamarin_4.6.1.exe", "0x8", "0x2570,0x0,0x48,0x50002,0x2070,0x4C8,0x3,0x6000002", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Read the Import Address Table from a file check the number of entries: HelloWorld" +
            "_Xamarin_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TextSection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "HelloWorld_Xamarin_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:File Name", "HelloWorld_Xamarin_4.6.exe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Number of Entries", "0x8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Entry Values", "0x2560,0x0,0x48,0x50002,0x2070,0x4C0,0x3,0x6000002")]
        public virtual void ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries_HelloWorld_Xamarin_4_6_Exe()
        {
            this.ReadTheImportAddressTableFromAFileCheckTheNumberOfEntries("HelloWorld_Xamarin_4.6.exe", "0x8", "0x2560,0x0,0x48,0x50002,0x2070,0x4C0,0x3,0x6000002", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
